import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define the API
export const spotifyApi = createApi({
  reducerPath: "spotifyApi",
  baseQuery: fetchBaseQuery({
    baseUrl: "https://spotify-web2.p.rapidapi.com",
    prepareHeaders: (headers) => {
      headers.set(
        "X-RapidAPI-Key",
        "c49b30e74bmshcca8fe1b10dbc7cp1b8c5ejsn22328292da5c"
      );
      headers.set("X-RapidAPI-Host", "spotify-web2.p.rapidapi.com");
      return headers;
    },
  }),
  endpoints: (builder) => ({
    getTopCharts: builder.query({
      query: () =>
        "/playlist_tracks/?id=37i9dQZF1DX4Wsb4d7NKfP&offset=0&limit=20",
    }),
  }),
});

// Export the hooks generated by the API
export const { useGetTopChartsQuery } = spotifyApi;
